baseURL = 'https://moonlab.iiserb.ac.in/'
defaultContentLanguage = 'en'
title = 'Multi Robot Autonomy Lab @ IISER Bhopal'
disableKinds = ["taxonomy", "term"]



[params]
  author = 'Moon Lab'
  description = 'Multi Robot Autonomy Lab @ IISER Bhopal'
  googleAnalyticsID = 'G-4391MGD2MB'
  logo = 'logo/moonlab.webp'
  google_fonts = [
    "Inter:wght@300;400;500;600",
    "Manrope:wght@400;500;700;800"
  ]



[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
  [[module.mounts]]
    source = 'static'
    target = 'assets'